### ISSUE TITLE
Add fallback environment variable

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/is-fork-pr#114]
To "support" other CI systems where standard CI environments are not found, we could use an environment variable `IS_FORK_PR` as a fallback. If it defined, we should return `true`

**Comment by bahmutov** [comment]
So thinking more about - by setting `IS_FORK_PR: true` for example, you will allow Cypress to use record key if available, or continue running tests with just a warning. This will take care of the stop in https://github.com/cypress-io/cypress/issues/1193#issuecomment-539599225 - just always have this env variable if expecting forked pull requests

**Comment by NicholasBoll** [comment]
That sounds reasonable
